import type { SupportRequest } from '@/lib/types';
import {
    Hexagon,
    Boxes,
    Network,
    Component,
    CloudCog,
    Link,
    Share2,
    Database,
    Binary,
    Shield,
    GitBranchPlus,
    Layers,
    Server,
    Zap,
    Cpu,
    Key,
    Package
} from 'lucide-react';

export const PROTOCOLS = [
  { name: 'Ethereum', icon: Hexagon },
  { name: 'Avalanche', icon: Boxes },
  { name: 'Binance', icon: Network },
  { name: 'Fantom', icon: Component },
  { name: 'Tron', icon: CloudCog },
  { name: 'Coreum', icon: Link },
  { name: 'Polkadot', icon: Share2 },
  { name: 'Polygon', icon: Database },
  { name: 'Provenance', icon: Binary },
  { name: 'Optimism', icon: Shield },
  { name: 'Arbitrum', icon: GitBranchPlus },
  { name: 'Base', icon: Layers },
  { name: 'Celestia', icon: Server },
  { name: 'Centrifuge', icon: Zap },
  { name: 'Etherlink', icon: Link },
  { name: 'Gnosis', icon: Hexagon },
  { name: 'Tezos', icon: Boxes },
  { name: 'Solana', icon: Network },
  { name: 'Flow', icon: Component },
  { name: 'XDC', icon: CloudCog },
  { name: 'Near', icon: Link },
  { name: 'Flare Chain', icon: Share2 },
  { name: 'Coti', icon: Database },
  { name: 'Subsquid', icon: Binary },
  { name: 'Injective', icon: Shield },
  { name: 'Glue', icon: GitBranchPlus },
  { name: 'Nillion', icon: Layers },
  { name: 'Kilt', icon: Key },
  { name: 'Unit', icon: Package },
  { name: 'Theta', icon: Zap },
  { name: 'Stellar', icon: Hexagon },
  { name: 'RPC', icon: Cpu },
  { name: 'Skale', icon: Network },
];


export const MOCK_REQUESTS: SupportRequest[] = [
  {
    id: 'REQ-001',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    type: 'Subscription',
    message: "I'm interested in the enterprise plan but I have a few questions about the number of API calls included. Can someone from sales reach out to me? We're a team of 50 developers.",
    timestamp: '2024-07-20T10:30:00Z',
    status: 'Requested',
  },
  {
    id: 'REQ-002',
    name: 'Bob Williams',
    email: 'bob@example.com',
    type: 'Contact',
    message: 'Hello, I am trying to integrate your service with a new DeFi project on the Polygon network. I am running into some authentication issues with the testnet credentials. The documentation is a bit unclear on the required headers. Could you please provide some clarification?',
    timestamp: '2024-07-20T09:15:00Z',
    status: 'Requested',
  },
  {
    id: 'REQ-003',
    name: 'Charlie Brown',
    email: 'charlie@example.com',
    type: 'Contact',
    message: 'My API key seems to have been compromised. I need to disable the old one and generate a new one immediately. Please guide me through the process as this is urgent.',
    timestamp: '2024-07-19T18:45:00Z',
    status: 'Requested',
  },
  {
    id: 'REQ-004',
    name: 'Diana Prince',
    email: 'diana@example.com',
    type: 'Subscription',
    message: 'We are a startup building a cross-chain bridge and we need a reliable RPC provider. We need support for Ethereum, Base, and Arbitrum. What are your pricing options for high-volume requests across multiple chains?',
    timestamp: '2024-07-19T14:00:00Z',
    status: 'Requested',
  },
    {
    id: 'REQ-005',
    name: 'Eva Green',
    email: 'eva@example.com',
    type: 'Contact',
    message: 'The latency for my requests to the Solana endpoint seems higher than usual over the past 24 hours. Is there an ongoing issue or maintenance? My application performance is being affected.',
    timestamp: '2024-07-21T11:00:00Z',
    status: 'Requested',
  },
];
