import {
    Hexagon,
    Boxes,
    Network,
    Component,
    CloudCog,
    Link,
    Share2,
    Database,
    Binary,
    Shield,
    GitBranchPlus,
    Layers,
    Server,
    Zap,
    Cpu,
    Key,
    Package
} from 'lucide-react';

export const PROTOCOLS = [
  { name: 'Ethereum', icon: Hexagon },
  { name: 'Avalanche', icon: Boxes },
  { name: 'Binance', icon: Network },
  { name: 'Fantom', icon: Component },
  { name: 'Tron', icon: CloudCog },
  { name: 'Coreum', icon: Link },
  { name: 'Polkadot', icon: Share2 },
  { name: 'Polygon', icon: Database },
  { name: 'Provenance', icon: Binary },
  { name: 'Optimism', icon: Shield },
  { name: 'Arbitrum', icon: GitBranchPlus },
  { name: 'Base', icon: Layers },
  { name: 'Celestia', icon: Server },
  { name: 'Centrifuge', icon: Zap },
  { name: 'Etherlink', icon: Link },
  { name: 'Gnosis', icon: Hexagon },
  { name: 'Tezos', icon: Boxes },
  { name: 'Solana', icon: Network },
  { name: 'Flow', icon: Component },
  { name: 'XDC', icon: CloudCog },
  { name: 'Near', icon: Link },
  { name: 'Flare Chain', icon: Share2 },
  { name: 'Coti', icon: Database },
  { name: 'Subsquid', icon: Binary },
  { name: 'Injective', icon: Shield },
  { name: 'Glue', icon: GitBranchPlus },
  { name: 'Nillion', icon: Layers },
  { name: 'Kilt', icon: Key },
  { name: 'Unit', icon: Package },
  { name: 'Theta', icon: Zap },
  { name: 'Stellar', icon: Hexagon },
  { name: 'RPC', icon: Cpu },
  { name: 'Skale', icon: Network },
];
